### ISSUE TITLE
不能加入koolproxyR

### ISSUE THREAD

**Issue by qy2009** [kang-mk/OpenWrt-Actions-Lean#3]
我试着加入,可是编译完了之后都没有...
git clone https://github.com/jefferymvp/luci-app-koolproxyR

CONFIG_PACKAGE_luci-app-koolproxyR=y

不知道是什么原因呢?

**Comment by qy2009** [comment]
另外,我试着删掉一个没有用的驱动...好像也是没用的?

# CONFIG_PACKAGE_kmod-8139cp is not set

**Comment by kang-mk** [comment]
git clone https://github.com/jefferymvp/luci-app-koolproxyR
后面需要附上文件路径 
具体看我前面示例

至于CONFIG_PACKAGE_kmod-8139cp is not set
前面需要加# 
# CONFIG_PACKAGE_kmod-8139cp is not set
这样才有效

**Comment by qy2009** [comment]
不好意思啊,第一次弄...
我不管怎么弄,编译的时候总是说:

> /home/runner/work/MyOpenWRT-Lean/MyOpenWRT-Lean/openwrt/.config:50: *** missing separator.  Stop.

不知道是为什么呢?

[OpenWrt-x86-64.txt](https://github.com/kang-mk/OpenWrt-Actions-Lean/files/4372529/OpenWrt-x86-64.txt)
